# Generated by Django 4.1.3 on 2022-12-23 19:52

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=backend.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
